name: github-actions

on:
  push:
    branches:
      - "staging"
      - "ymc/deploy-cloud-run"

env:
  REPOSITORY: ${{ github.event.repository.name }}
  FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo Repo and Branch
        run:  |
          echo "Repository: $REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Prepare Stg Envs
        if:  contains(fromJson('["staging","ymc/deploy-cloud-run"]'), env.BRANCH)
        env: 
          SERVICE_ACCOUNT: ${{ secrets.NIFFLER_FIREBASE_SERVICE_ACCOUNT_STG }}
          CLOUD_RUN_SERVICE_ACCOUNT_FILE_NIFFLER: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_FILE_NIFFLER_STG }}
        run: |
          echo "BRANCH=staging" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ vars.NIFFLER_FIREBASE_PROJECT_ID_STG }}" >> $GITHUB_ENV
          echo "IMAGE_NAME"=niffler-backend-api:stglatest >> $GITHUB_ENV
          echo "GCLOUD_REPO_REGION=asia-southeast1-docker.pkg.dev" >> $GITHUB_ENV
          echo "GCLOUD_REPO_NAME=$GCLOUD_REPO_REGION/niffler-stg" >> $GITHUB_ENV
          printf "%s" "$SERVICE_ACCOUNT" > service-account.json
          printf "%s" "$CLOUD_RUN_SERVICE_ACCOUNT_FILE_NIFFLER" > could-run-service-account.json

      - name: Prepare Prod Envs
        if:  contains(fromJson('["production"]'), env.BRANCH)
        env:
          SERVICE_ACCOUNT: ${{ secrets.NIFFLER_FIREBASE_SERVICE_ACCOUNT_STG }}
          CLOUD_RUN_SERVICE_ACCOUNT_FILE_NIFFLER: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_FILE_NIFFLER }}
        run: |
          echo "BRANCH=production" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ vars.NIFFLER_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "IMAGE_NAME"=niffler-backend-api:latest >> $GITHUB_ENV
          echo "GCLOUD_REPO_REGION=asia-southeast1-docker.pkg.dev" >> $GITHUB_ENV
          echo "GCLOUD_REPO_NAME=$GCLOUD_REPO_REGION/niffler" >> $GITHUB_ENV
          printf "%s" "$SERVICE_ACCOUNT" > service-account.json
          printf "%s" "$CLOUD_RUN_SERVICE_ACCOUNT_FILE_NIFFLER" > could-run-service-account.json

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Image to Docker Hub
        id: push-latest
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ymcsabo/${{ env.IMAGE_NAME }}
          push: true
          cache-from: type=gha,scope=build-${{ env.REGISTRY_NAME }}

      - name: Install gCloud Run CLI
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates gnupg curl
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install google-cloud-cli
      
      - name: gCloud CLI login
        run: |
          gcloud auth login --no-launch-browser --cred-file=could-run-service-account.json
          gcloud config set project $PROJECT_ID
          gcloud auth list

      - name: Deploy to Cloud Run
        run: |
          docker pull ymcsabo/${{ env.IMAGE_NAME }}
          docker tag ymcsabo/${{ env.IMAGE_NAME }} ${{ env.GCLOUD_REPO_NAME }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.GCLOUD_REPO_NAME }}/${{ env.IMAGE_NAME }}
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          gcloud run deploy niffler-backend-api --image ${{ env.GCLOUD_REPO_NAME }}/${{ env.IMAGE_NAME }} --region asia-east1


      


